### ISSUE TITLE
Unicode exception for package-zip

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#218]
In the logs for prod3. Looks like a '£' in the filename is causing problems.

```
2015-11-01 19:05:18
  raised exception
  UnicodeEncodeError('ascii', u'/mnt/shared/ckan_resource_cache/c2/c2542a87-af5f-4038-ae70-1b1ee7a2be0f/GSCC_spend_over_\xa325k_April2010.csv', 88, 89, 'ordinal not in range(128)')
  Traceback (most recent call last):
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/src/ckanext-packagezip/ckanext/packagezip/tasks.py", line 65, in create_zip
    if res['cache_filepath'] and os.path.exists(res['cache_filepath']):
  File "/home/co/ckan/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 88: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/src/ckanext-packagezip/ckanext/packagezip/tasks.py", line 65, in create_zip
    if res['cache_filepath'] and os.path.exists(res['cache_filepath']):
  File "/home/co/ckan/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 88: ordinal not in range(128)
```

**Comment by morty** [comment]
This one has been a real pain to diagnose (as are all unicode issues).

Firstly any new resources with non-ascii characters in the file name will have them removed when it is saved by the archiver:

https://github.com/datagovuk/ckanext-archiver/commit/e069f2f9e96cc40f69bafe7a4e736c0e6af25f9b

I believe this issue is caused by the LANG environment variable not being set by Supervisor (I have seen similar issues with CRON). This can be demonstrated by running the following command on Linux:

```
LANG=C python -c "import os; os.stat(u'\xa3')"
```

I have added ```LANG="en_GB.utf8", LC_ALL="en_GB.UTF-8", LC_LANG="en_GB.UTF-8"``` to the environment setting in ```/etc/supervisor/supervisord.conf``` and will check to see that it is now generating the zip file for a package with resources that have non-ascii characters.

**Comment by morty** [comment]
I should have said that I have changed the settings only on prod2 currently.

**Comment by morty** [comment]
Deployed on live and is working well.
