### ISSUE TITLE
Script to update missing formats from QA

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#293]

**Comment by rossjones** [comment]
First run (which showed a bug wrt None)->

```
    Updating format to HTML: 27917 
    Updating format to XML: 5988 
    Updating format to WMS: 1224
    Updating format to None: 465 
    Updating format to PDF: 279 
    Updating format to CSV: 222 
    Updating format to KML: 105 
    Updating format to RTF: 93
    Updating format to RDFa: 92
    Updating format to XLS: 92 
    Updating format to SHP: 45
    Updating format to TIFF: 29 
    Updating format to JSON: 10
    Updating format to TXT: 4 
    Updating format to DOC: 4
    Updating format to Zip: 3 
    Updating format to RDF: 1 
    Updating format to RSS: 1 

```

**Comment by rossjones** [comment]
On a second run (after using -w to write more than once) I get the following exception. Which is not very good.

```
Traceback (most recent call last):
  File "ckanext/dgu/bin/set_missing_resource_formats.py", line 92, in <module>
    cmd.run(options)
  File "ckanext/dgu/bin/set_missing_resource_formats.py", line 66, in run
    self.ckan.action.package_update(**pkg)
  File "/home/co/ckan/local/lib/python2.7/site-packages/ckanapi/common.py", line 51, in action
    return self._ckan.call_action(name, data_dict=kwargs)
  File "/home/co/ckan/local/lib/python2.7/site-packages/ckanapi/localckan.py", line 50, in call_action
    return self._get_action(action)(dict(context), dict(data_dict))
  File "/src/ckan/ckan/logic/__init__.py", line 425, in wrapped
    result = _action(context, data_dict, **kw)
  File "/src/ckan/ckan/logic/action/update.py", line 334, in package_update
    pkg = model_save.package_dict_save(data, context)
  File "/src/ckan/ckan/lib/dictization/model_save.py", line 315, in package_dict_save
    package_membership_list_save(pkg_dict.get("groups"), pkg, context)
  File "/src/ckan/ckan/lib/dictization/model_save.py", line 233, in package_membership_list_save
    model.Session.flush()
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 114, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1583, in flush
    self._flush(objects)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1654, in _flush
    flush_context.execute()
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 331, in execute
    rec.execute(self)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 475, in execute
    uow
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 59, in save_obj
    mapper, table, update)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _emit_update_statements
    execute(statement, params)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1449, in execute
    params)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (IntegrityError) insert or update on table "resource" violates foreign key constraint "resource_revision_id_fkey"
DETAIL:  Key (revision_id)=(36e633bb-a705-45eb-b60f-0e7919f64857) is not present in table "revision".
 'UPDATE resource SET revision_id=%(revision_id)s WHERE resource.id = %(resource_id)s' {'revision_id': u'36e633bb-a705-45eb-b60f-0e7919f64857', 'resource_id': u'10f80ddf-be7b-4b4f-94b6-9d2341b53aea'}
```

**Comment by rossjones** [comment]
```ckan=# select * from revision where id='10f80ddf-be7b-4b4f-94b6-9d2341b53aea';
(No rows)
```

There are however 3 revisions.

**Comment by davidread** [comment]
Is all sorted if you create it? If not then we need to find all the occurences i guess

**Comment by rossjones** [comment]
Now have the situation where the resource *does* actually exist,  and it has valid resource_revisions, but it is failing to set the revision id in the resource table.  The revision it thinks it has added does not exist, hence the error.

Presumably this will happen if there is a failure to save the revision (after having created the ID for it).

**Comment by davidread** [comment]
So again I guess you create the revision. If there's more than a handful then maybe we should look harder at these.

**Comment by rossjones** [comment]
These aren't existing broken resources, they're broken after the first run, and there's no revision_create in the API.  Will do as you suggest though and just handle it and carry on to see how many break.

**Comment by davidread** [comment]
Ah I understand now. Let's not cause any problems - sounds like getting stuck in to debug it is needed.

**Comment by rossjones** [comment]
Latest run on prod 2:

```
        Updating format to HTML: 7516
        Updating format to XML: 248
        Updating format to CSV: 43 
        Updating format to KML: 42 
        Updating format to WMS: 31
        Updating format to PDF: 30
        Updating format to RTF: 16 
        Updating format to RDFa: 5 
        Updating format to SHP: 4 
        Updating format to TIFF: 4 
        Updating format to JSON: 2
        Updating format to Zip: 1
        Packages updated: 1851
        Time taken (h:m:s): 0:46:27.716749
```

Re-running to make sure it didn't introduce any errors into the data.

**Comment by davidread** [comment]
Concerned it might have caused #303. I'll try it on my box.

**Comment by rossjones** [comment]
Performed the following tasks.

* Reset the DB
* Did a reindex
* Run the script
* Did a reindex

The last reindex fails in the way we're seeing on prod2 with the following exception.

```
Indexing dataset 9458/253752016-01-14 21:28:04,131 ERROR [ckan.lib.search] Error while indexing dataset e28d08b5-3bc5-4c96-908a-fd10903c31db:
Traceback (most recent call last):
  File "/home/co/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/src/ckan/ckan/lib/cli.py", line 484, in command
    self.rebuild()
  File "/src/ckan/ckan/lib/cli.py", line 556, in rebuild
    quiet=self.options.quiet)
  File "/src/ckan/ckan/lib/search/__init__.py", line 199, in rebuild
    {'id': pkg_id}
  File "/src/ckan/ckan/logic/__init__.py", line 425, in wrapped
    result = _action(context, data_dict, **kw)
  File "/src/ckan/ckan/logic/action/get.py", line 925, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/src/ckan/ckan/lib/dictization/model_dictize.py", line 212, in package_dictize
    raise logic.NotFound
ckan.logic.NotFound
```

It appears something the script is doing is breaking the package.

**Comment by rossjones** [comment]
Using the first failing dataset I...

1. Rebuilt my solr index
2. Ran the script with this output (a fail)

```
python ckanext/dgu/bin/set_missing_resource_formats.py $CKAN_INI -d e28d08b5-3bc5-4c96-908a-fd10903c31db -w
DATASET: doe-development-plans-wms had a validation error: {‘spatial’: [u’Error decoding JSON object: Expecting value: line 1 column 36 (char 35)’]}
```

3. paster search-index rebuild -r doe-development-plans-wms
4. Re-index succeeds!
5. Serve and go to http://192.168.11.11:5000/datasset/doe-development-plans-wms
6. Got 404.

Working hypothesis ... revision was created, package_update failed, original revision no longer there.

**Comment by davidread** [comment]
doe-development-plans-wms has no spatial extent. It got into DGU because was harvested before we applied strict validation to UKLP datasets in 2013. Since it's still not been updated, I've just deleted it.

I think we *should* have an exception if we get an error storing the spatial extent. It would be good to work out why the dataset 404s though. I see that in this case the commit of the package_update is not done, but it sounds like part of it does. But I've run the script now locally and on prod2 and can't see this happening with any more datasets, so I'll assume we don't have this problem any more.

**Comment by davidread** [comment]
Ran locally on prod3. Also added to cron for Friday night, to catch any newly harvested datasets.
Output:
```
(ckan)co@prod3 /vagrant/src/ckanext-dgu (master) $ python ../ckanext-dgu/ckanext/dgu/bin/set_missin
g_resource_formats.py $CKAN_INI -w
Connecting to CKAN...
...connected.
/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage o
f the 'related attribute set' operation is not currently supported within the execution stage of th
e flush process. Results may not be consistent.  Consider using alternative event listeners or conn
ection-level operations instead.
  sess._flush_warning("related attribute set")
DATASET: camden-neighbourhood-boundaries had a validation error: {u'additional_resources': [{'descr
iption': ['Missing value']}], u'individual_resources': [{'description': ['Missing value']}, {'descr
iption': ['Missing value']}, {'description': ['Missing value']}, {'description': ['Missing value']}
, {'description': ['Missing value']}, {'description': ['Missing value']}]}
DATASET: directgov-section-visits-monthly had a validation error: {u'individual_resources': [{'desc
ription': ['Missing value'], 'format': ['Missing value']}]}
DATASET: tree-preservation-order-polygon had a validation error: {'notes': ['Missing value']}
DATASET: tree-preservation-order-polygons had a validation error: {'notes': ['Missing value']}
DATASET: tree-preservation-orders-points1 had a validation error: {'notes': ['Missing value']}
DATASET: tree-preservation-orders-points2 had a validation error: {'notes': ['Missing value']}
DATASET: uk-civil-service-jobs had a validation error: {u'individual_resources': [{'description': [
'Missing value']}]}
DATASET: uk-export-control-statistics had a validation error: {u'individual_resources': [{'descript
ion': ['Missing value']}]}
DATASET: uk-exportcontrol-sanctions had a validation error: {u'individual_resources': [{'descriptio
n': ['Missing value']}], 'date_released': ["Cannot parse form date 'Prior to 2005'. Acceptable form
ats: 'DD/MM/YYYY HH:MM', 'HH:MM DD/MM/YYYY', 'DD/MM/YYYY', 'MM/YYYY', 'YYYY'"]}
DATASET: uk-exportcontrollists had a validation error: {u'individual_resources': [{'description': [
'Missing value']}], 'date_released': ["Cannot parse form date 'Prior to 2005'. Acceptable formats:
'DD/MM/YYYY HH:MM', 'HH:MM DD/MM/YYYY', 'DD/MM/YYYY', 'MM/YYYY', 'YYYY'"]}
DATASET: uk-glossary-exportcontrol had a validation error: {u'individual_resources': [{'description': ['Missing value']}], 'date_released': ["Cannot parse form date 'Prior to 2005'. Acceptable formats: 'DD/MM/YYYY HH:MM', 'HH:MM DD/MM/YYYY', 'DD/MM/YYYY', 'MM/YYYY', 'YYYY'"]}
DATASET: uk-ipo-offences had a validation error: {u'individual_resources': [{'description': ['Missing value']}], 'date_released': ["Cannot parse form date 'not known'. Acceptable formats: 'DD/MM/YYYY HH:MM', 'HH:MM DD/MM/YYYY', 'DD/MM/YYYY', 'MM/YYYY', 'YYYY'"]}

        Updating format to HTML: 3207 [u'7f3a1ff8-8c85-4363-b7b9-135e1b9e6cfa', u'8f1aa34c-168d-487
4-9125-c9b3869ca6a4', u'6f0fdce7-6c52-4a58-b5b9-4430ac7c8e79', u'1b35f64a-1378-46aa-...
        QA format empty: 431 [u'2024c2e2-2219-4db6-adb1-b3e7bffb533c', u'7d0c769f-cde7-429d-a7d4-48
21655913f0', u'3f089744-9a66-40f3-9cc0-d2f2736e86f4', u'5d56bc4d-e4e9-40e2-9...
        Updating format to XML: 295 [u'a2636d7a-c980-48ca-b730-f697f7294bf5', u'879132e1-abee-4c94-
9935-c7abe9f6d62e', u'25aed48c-4177-4c1c-ac2f-81981e41b47f', u'cf809e61-106e-4ff0-8...
131-8799cffab165', u'2ed4eb78-b3c4-40d9-9c5d-49200996b94b', u'09fc2155-faca-4179-b4...
        Updating format to RTF: 28 [u'cdc65682-ef42-42cc-9315-6af22339b2b7', u'1276dc19-2ab7-42a9-a406-fe431f20e670', u'cc9fc7e3-3153-4e4b-8a96-367c4c50ad77', u'5a36c14d-867a-4be5-a1...
        Updating format to PDF: 27 [u'80897940-b351-4bc2-86de-bb90e559d10d', u'8150cdf8-5884-4525-9678-dff2e1a51fd8', u'8ad4e58f-1c4a-40ee-ba56-e09500f5792f', u'df7f6885-366d-41e2-9c...
        Updating format to XLS: 17 [u'0b7047d6-aa8f-4540-82fc-036bbe82170f', u'1fb1c29e-5a13-49d3-9469-4273bd4208e0', u'2044760a-9847-4e66-bb8a-4012edf18516', u'16f96bc1-f6c0-4141-b4...
        Updating format to KML: 10 [u'f9ea4d8d-7337-49cc-80bf-0991ac7e40b3', u'2e58813d-38d0-4a8c-9c3c-d6dc5a48b0cf', u'1770c651-1db0-4d24-853a-d92a854ba27a', u'f959fe12-23bd-4521-86...
        Updating format to SHP: 9 [u'1d332647-a405-43fc-867f-60ba5bed88e2', u'c3b36d41-9d4c-4054-88ca-21a43121909c', u'ac6cbb6f-f665-4fc4-bf11-248f5daaabac', u'aec2a180-7b66-4691-abc...
        Updating format to RDFa: 2 [u'e3d29bc2-2455-4d59-bb9f-8020f5d60ad8', u'208bd0e9-e457-44b1-9dde-fd56fbbb0011']
        Updating format to DOC: 2 [u'9e21406e-af52-4c98-9091-b8561ef68d76', u'3293cf24-dbfb-4584-9afb-44686caec85c']
        Updating format to JSON: 2 [u'965a7d94-c8f2-4c82-95b6-26e22dc7832e', u'fde7da4c-9224-4f01-a4be-f9f899aa427c']
        Updating format to RSS: 1 [u'bf560fce-7460-4343-acd6-00f1c3c6991b']
        Time taken (h:m:s): 0:23:01.340215
        Packages updated: 1584 [u'27c45308-2f90-4896-98ce-2b189e485253', u'b8db15af-88f5-4c9b-b2cd-bb336934200f', u'a421f548-0fe0-47bb-93a8-9d86896fdfa9', u'de6c5f3f-d9e6-4321-...
        Time taken (h:m:s): 0:23:01.341884
```
Before:
HTML (10678)
XML (6027)
CSV (4476)
WMS (3668)
XLS (1790)
PDF (905)
RDF (214)
Zip (197)
KML (196)
ODS (180)

After:
HTML (11592)
XML (6308)
CSV (4516)
WMS (3808)
XLS (1791)
PDF (932)
RDF (214)
KML (206)
Zip (197)
ODS (180)
