### ISSUE TITLE
Missing current field in some package revisions

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#304]
It appears to be possible for some package_revisions to be created where current=NULL.  

This is:

1. Something that we should ensure is not possible.

2. Undesirable.

**Comment by davidread** [comment]
I found a single dataset like this last week when doing a reindex (it breaks the reindex). Details of it are below. I'm not sure how it appeared, but it seems to have been kicking around since 2016-02-10. Since it's such a rare problem, we should not agonize on why it's being generated.

However I've added a simple function that cleans-up this if it is found. It's in the `current_revision.py` script which was for cleaning up the same problem with resources that we had before, and still gets run by cron every morning.

```
(ckan)co@prod2 ~ () $ /home/co/ckan/bin/paster --plugin=ckan search-index rebuild -r --config=$CKAN_INI 4eb0ab41-7671-43cd-91df-1ec9195f951b
2016-05-02 12:05:12,461 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2016-05-02 12:05:12,465 DEBUG [ckanext.harvest.model] Harvest tables already exist
2016-05-02 12:05:12,481 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2016-05-02 12:05:12,487 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2016-05-02 12:05:12,559 INFO  [ckan.lib.search] Rebuilding search index...
Traceback (most recent call last):
  File "/home/co/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 484, in command
    self.rebuild()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 550, in rebuild
    rebuild(self.args[1])
  File "/vagrant/src/ckan/ckan/lib/search/__init__.py", line 157, in rebuild
    {'id': package_id})
  File "/vagrant/src/ckan/ckan/logic/__init__.py", line 425, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/src/ckan/ckan/logic/action/get.py", line 925, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/vagrant/src/ckan/ckan/lib/dictization/model_dictize.py", line 186, in package_dictize
    raise logic.NotFound
ckan.logic.NotFound

<Package id=4eb0ab41-7671-43cd-91df-1ec9195f951b name=roads-service-assets-wms title=Roads Service Assets (WMS) version=None url=None author=None author_email=None maintainer=None maintainer_email=None notes=This service contains information from DRD Roads Service. This information includes: bridges, illuminated bollards and signs and street lighting. For more information see individual layers. license_id= type=dataset owner_org=cd937140-1310-4e2a-b211-5de8bebd910d creator_user_id=60e687bf-a6d8-43e2-a50e-efab84b27952 metadata_modified=2016-02-10 17:01:09.693229 private=False state=active revision_id=4d70a85b-0b41-4f21-97a0-80e0e46e6e2d>

(Pdb) for pr in model.Session.query(model.PackageRevision).filter_by(id=pkg.id): print pr
<PackageRevision id=4eb0ab41-7671-43cd-91df-1ec9195f951b name=roads-service-assets-wms title=Roads Service Assets (WMS) version=None url=None author=None author_email=None maintainer=None maintainer_email=None notes=This service contains information from DRD Roads Service. This information includes: bridges, illuminated bollards and signs and street lighting. For more information see individual layers. license_id=None type=None owner_org=cd937140-1310-4e2a-b211-5de8bebd910d creator_user_id=None metadata_modified=None private=False state=active revision_id=fb152260-1317-4fdc-b41c-cc454101ae4d continuity_id=4eb0ab41-7671-43cd-91df-1ec9195f951b expired_id=657ed1b7-67ba-4497-a5ef-37fa23157418 revision_timestamp=2013-03-01 14:31:49.340577 expired_timestamp=2016-02-10 17:01:09.803109 current=False>
<PackageRevision id=4eb0ab41-7671-43cd-91df-1ec9195f951b name=roads-service-assets-wms title=Roads Service Assets (WMS) version=None url=None author=None author_email=None maintainer=None maintainer_email=None notes=This service contains information from DRD Roads Service. This information includes: bridges, illuminated bollards and signs and street lighting. For more information see individual layers. license_id= type=dataset owner_org=cd937140-1310-4e2a-b211-5de8bebd910d creator_user_id=60e687bf-a6d8-43e2-a50e-efab84b27952 metadata_modified=2016-02-10 17:01:09.693229 private=False state=active revision_id=4d70a85b-0b41-4f21-97a0-80e0e46e6e2d continuity_id=4eb0ab41-7671-43cd-91df-1ec9195f951b expired_id=657ed1b7-67ba-4497-a5ef-37fa23157418 revision_timestamp=None expired_timestamp=2016-02-10 17:01:09.803109 current=None>
NB
* no revision_timestamp
* current is None
```
