### ISSUE TITLE
Missing datasets in search index

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#417]
We had about 30k datasets at https://data.gov.uk/data/search on Friday and today we have 23k.

They appear to be in the database, but not the search index.

**Comment by davidread** [comment]
```
[2016-05-08 10:32:36,540: ERROR/MainProcess] Task qa.update_package[zones-2014-631a] raised exception: SearchIndexError('Solr returned an error: 500 Server Error - <?xml version="1.0" enc
oding="UTF-8"?>\n<response>\n<lst name="responseHeader"><int name="status">500</int><int name="QTime">3</int></lst><lst name="error"><str name="msg">Error logging add</str><str name="trac
e">org.apache.solr.common.SolrException: Error logging add\n\tat org.apache.solr.update.TransactionLog.write(TransactionLog.java:373)\n\tat org.apache.solr.update.UpdateLog.add(UpdateLog.
java:366)\n\tat org.apache.solr.update.UpdateLog.add(UpdateLog.java:351)\n\tat org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:229)\n\tat org.apache.solr.upda
te.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)\n\tat org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)\n\ta
t org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:519)\n\tat org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(
DistributedUpdateProcessor.java:655)\n\tat org.apache.solr.upd',)
Traceback (most recent call last):
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/co/ckan/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/src/ckanext-qa/ckanext/qa/tasks.py", line 68, in update_package
    update_package_(package_id, log)
  File "/vagrant/src/ckanext-qa/ckanext/qa/tasks.py", line 93, in update_package_
    _update_search_index(package.id, log)
  File "/vagrant/src/ckanext-qa/ckanext/qa/tasks.py", line 420, in _update_search_index
    package_index.index_package(package, defer_commit=False)
  File "/vagrant/src/ckan/ckan/lib/search/index.py", line 280, in index_package
    raise SearchIndexError(msg)
SearchIndexError: Solr returned an error: 500 Server Error - <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">500</int><int name="QTime">3</int></lst><lst name="error"><str name="msg">Error logging add</str><str name="trace">org.apache.solr.common.SolrException: Error logging add
        at org.apache.solr.update.TransactionLog.write(TransactionLog.java:373)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:366)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:351)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:229)
        at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:519)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:655)
        at org.apache.solr.upd
```

**Comment by davidread** [comment]
I've reindexed the missing ones and got all 31169 datasets to appear again now.

    paster --plugin=ckan search-index rebuild -o -r -c $CKAN_INI

Now to look at why SOLR wasn't indexing.

**Comment by davidread** [comment]
The errors occurred mostly 3am to 11am on 8/5/16, which is when the prod3 main disk was full, which explains why SOLR couldn't index.
